"""empty message

Revision ID: d97982780622
Revises: a2f50305de5c
Create Date: 2019-11-10 12:57:46.853633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97982780622'
down_revision = 'a2f50305de5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('state', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'state')
    # ### end Alembic commands ###
